### PR TITLE
Lza/release

### PR DESCRIPTION
**Pull request by zdlm**
@esmailpour-hosein @aleks-elkin

### CODE REVIEW

**Comment by esmailpour-hosein** [comment]
Why you have 3 patch? 🤔

**Comment by zdlm** [comment]
Because I made something wrong. I didn't create a branch at the first time. The opt was expired while publishing.

**Comment by esmailpour-hosein** [comment]
For the next time that it happened you can just delete the tags and release on github by this commands:

```
# delete local tag '12345'
git tag -d 12345
# delete remote tag '12345' (eg, GitHub version too)
git push origin :refs/tags/12345
# alternative approach
git push --delete origin tagName
git tag -d tagName
```

and then deleting the branch and create another one 👍

**Comment by zdlm** [comment]
Good job. I will put it into readme for publishing.

**Comment by esmailpour-hosein** [comment]
Greate, We also need to fix the process, so it should do couple of other checks before just creating the tags so we won't end up in that situation

**Pull request merged**
